Linked licences fusioncode
IMIO/Products.urban pull request #129
Opened 2021-11-30 14:59 UTC by jjaumotte

Pourrais-tu me faire part de tes remarques/améliorations ? Voici le ticket lié : https://support.imio.be/browse/MURBECAA-52
Merci.

2021-12-03 13:27 UTC, sdelcourt commented on src/Products/urban/docgen/helper_view.py
> +                licence_review_state = workflow.getInfoFor(licence, 'review_state')
use plone.api instead

2021-12-03 13:29 UTC, sdelcourt requested changes
Add a unit test ;-)

2021-12-03 13:29 UTC, sdelcourt commented on src/Products/urban/docgen/helper_view.py
> +    def get_related_licences(self, licence_types=[], decision_limit_date=None, decision_event_status='', licence_status=None):
use 'state' rather than 'status'

2021-12-03 13:29 UTC, sdelcourt commented on src/Products/urban/docgen/helper_view.py
> +            licences_status = []
use something more different from licence_status

2022-01-19 16:15 UTC, jjaumotte commented on src/Products/urban/docgen/helper_view.py
> +            licences_status = []
Fix variable name

2022-01-19 16:16 UTC, jjaumotte commented on src/Products/urban/docgen/helper_view.py
> +    def get_related_licences(self, licence_types=[], decision_limit_date=None, decision_event_status='', licence_status=None):
Fix variable name

2022-01-19 16:18 UTC, jjaumotte commented
Add unit tests for "with_historic" param

2022-02-02 13:23 UTC, sdelcourt approved these changes
all good (-:

2022-02-02 13:23 UTC, merged