Urb 2220 publipostage personne de contact
IMIO/Products.urban pull request #145
Opened 2022-04-04 14:04 UTC by MagDhyIm

Can you check then merge if it's ok ?

2022-04-05 06:28 UTC, sdelcourt requested changes

2022-04-05 06:28 UTC, sdelcourt commented on src/Products/urban/Corporation.py
> +    StringField(
personContactNomduChamp est plus cohérent

2022-04-05 06:28 UTC, sdelcourt commented on src/Products/urban/browser/templates/contactmacros.pt
> +                    <span> (adresse siege social)</span>
utiliser une vraie traduction

2022-04-05 06:28 UTC, sdelcourt commented on src/Products/urban/docgen/helper_view.py
> +    def correction_corporation_contact(self, mailing_l):
Je pense qu'il y a de meilleures solutions possibles que de réassigner automatiquement des champs précédement encodés à la main avec des valeurs d'autre champs.

2022-04-05 06:28 UTC, sdelcourt commented on src/Products/urban/docgen/helper_view.py
> +                if self.real_context.getParentNode().portal_type in licencenv:
le publipostage des personnes morales n'est pas restreint aux permis d'environnement

2022-04-27 09:38 UTC, MagDhyIm commented on src/Products/urban/Corporation.py
> +    StringField(
done

2022-04-27 10:10 UTC, MagDhyIm reviewed
changes done

2022-05-09 09:03 UTC, sdelcourt approved these changes

2022-05-09 09:03 UTC, merged